version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.4
    working_directory: ~/konojunya.com
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: npm test
      - deploy:
        name: sakura vps
        commands:
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            ssh konojunya@153.126.171.5 -p 9733
            cd /var/www/html/konojunya.com
            git pull origin master
            pm2 reload konojunya.com
          fi
