version: 2
jobs:
  build:
    working_directory: ~/konojunya.com
    docker:
      - image: circleci/node:8.1.4

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules
      - run:
          name: test
          command: npm test
