version: 2
jobs:
  build:
    working_directory: ~/konojunya.com
    docker:
      - image: circleci/node:8.1.4

    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
