version: 2
jobs:

  test:
    working_directory: ~/konojunya.com
    docker:
      - image: makki0205/deploy

    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: coverage
          command: env COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run cover
      - save_cache:
          key: node-{{ epoch }}
          paths:
            - .

  deploy:
    working_directory: ~/konojunya.com
    docker:
      - image: makki0205/deploy

    steps:
      - checkout
      - restore_cache:
          keys:
            - node
      - run:
          name: generate
          command: npm run generate
      - run:
          name: aws login
          command: make aws/credentials
      - run:
          name: deploy
          command: make aws/deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
